### ISSUE TITLE
Missing Word List (Mineplex)

### ISSUE THREAD

**Issue by Chew** [Croutonix/dmtcheat#5]
# Official Missing Word List for Mineplex's Draw My Thing

## How to submit a missing word
Simply respond below with the missing word, and if you could please provide a screenshot to help verify your word. We will add the word when we see it.

#### Commit b642229
[lighthouse](#issuecomment-315649241) (No Screenshot)
#### Commit 8bdfe89
[round](#issuecomment-315837596)
[Restaurant](#issuecomment-315837596)
[Fishing pole](#issuecomment-315837596)
[stage](#issuecomment-315837596)
[pineapple](#issuecomment-315837596)
[baseball](#issuecomment-315837596)
#### Commit 266b326
[birthday cake](#issuecomment-315854120)
[knot](#issuecomment-315854120)
#### Commit e78b84d
[Hair dryer](#issuecomment-317260520) (Thanks [Echotiized](https://github.com/Echotiized))
[Hula hoop](#issuecomment-317260520) (Thanks [Echotiized](https://github.com/Echotiized))
[Mailman](#issuecomment-317260520) (Thanks [Echotiized](https://github.com/Echotiized))
[Song](#issuecomment-317260520) (Thanks [Echotiized](https://github.com/Echotiized))
[Chin](#issuecomment-317260520) (Thanks [Echotiized](https://github.com/Echotiized))
[Popcorn](#issuecomment-317260520) (Thanks [Echotiized](https://github.com/Echotiized)) (No Screenshot)
#### Commit 36033d6
Cup
#### Commit 92f7e01
[watering can](#issuecomment-317899672) (Thanks [MrJoCrafter](http://github.com/MrJoCrafter)) (No Screenshot)
[plate](#issuecomment-317899672) (Thanks [MrJoCrafter](http://github.com/MrJoCrafter)) (No Screenshot)
[zoo](#issuecomment-317961958) (Thanks [Echotiized](https://github.com/Echotiized)) (No Screenshot)
[state](#issuecomment-318160509) (Thanks [MrJoCrafter](http://github.com/MrJoCrafter)) (No Screenshot)

## Words Added
_Let's make a fun contest?_
[Chewsterchew](http://github.com/Chewsterchew) - 9 Words
[Echotiized](https://github.com/Echotiized) - 7 Words
[MrJoCrafter](http://github.com/MrJoCrafter) - 3 Words

**Comment by Chew** [comment]
I guess I should elaborate more, lighthouse is the word.

**Comment by Croutonix** [comment]
Thanks! What do you think of the new version?

**Comment by Chew** [comment]
<img width="417" alt="4ddea291c433add27ea137c582c0f590" src="https://user-images.githubusercontent.com/8278263/28283111-4eba06be-6af2-11e7-987a-9316a93cd107.png">
<img width="458" alt="13fee58480904b10787f192c66ea0890" src="https://user-images.githubusercontent.com/8278263/28283229-bbef6490-6af2-11e7-84dd-e4ae8495047d.png">
<img width="459" alt="47e9e22497fd0c7a411f163b6fc3e8f2" src="https://user-images.githubusercontent.com/8278263/28283786-7a037b28-6af4-11e7-967b-c19c0ec0218d.png">
<img width="406" alt="cc9a47bbb1bca0317ec24a89b8591341" src="https://user-images.githubusercontent.com/8278263/28284191-bd6dd0ce-6af5-11e7-80d9-3e729fbb5db8.png">
<img width="443" alt="88c2fb6d396a337cb72506ac52914197" src="https://user-images.githubusercontent.com/8278263/28284678-6c134428-6af7-11e7-9265-6769f6724c0d.png">
<img width="435" alt="25b153221fc8441c5c9f31580134e8d1" src="https://user-images.githubusercontent.com/8278263/28284993-b09f67d8-6af8-11e7-8b3f-c1bf32ed401a.png">

##### _Edit: I combined all of mine so it's easier to follow <3_

**Comment by Chewsterchew** [comment]
Another word: Restaurant
<img width="458" alt="13fee58480904b10787f192c66ea0890" src="https://user-images.githubusercontent.com/8278263/28283229-bbef6490-6af2-11e7-84dd-e4ae8495047d.png">

**Comment by Chewsterchew** [comment]
Another word: Fishing pole
<img width="459" alt="47e9e22497fd0c7a411f163b6fc3e8f2" src="https://user-images.githubusercontent.com/8278263/28283786-7a037b28-6af4-11e7-967b-c19c0ec0218d.png">

**Comment by Chewsterchew** [comment]
Word: stage
<img width="406" alt="cc9a47bbb1bca0317ec24a89b8591341" src="https://user-images.githubusercontent.com/8278263/28284191-bd6dd0ce-6af5-11e7-80d9-3e729fbb5db8.png">

**Comment by Chewsterchew** [comment]
pineapple
<img width="443" alt="88c2fb6d396a337cb72506ac52914197" src="https://user-images.githubusercontent.com/8278263/28284678-6c134428-6af7-11e7-9265-6769f6724c0d.png">

**Comment by Chewsterchew** [comment]
word: baseball
<img width="435" alt="25b153221fc8441c5c9f31580134e8d1" src="https://user-images.githubusercontent.com/8278263/28284993-b09f67d8-6af8-11e7-8b3f-c1bf32ed401a.png">

**Comment by Croutonix** [comment]
The 6 words were added! Thanks for the screenshots!

**Comment by Chew** [comment]
<img width="482" alt="2dbfa34c268b5fee8a8cf623f8103617" src="https://user-images.githubusercontent.com/8278263/28285511-a950e6f8-6afa-11e7-93d4-e3e8350dc5fc.png">
<img width="396" alt="417f8f011a49a9655837c9e1ee0874bc" src="https://user-images.githubusercontent.com/8278263/28297467-b8405520-6b33-11e7-96f8-731797b27b46.png">

**Comment by Chewsterchew** [comment]
Another one: knot
<img width="396" alt="417f8f011a49a9655837c9e1ee0874bc" src="https://user-images.githubusercontent.com/8278263/28297467-b8405520-6b33-11e7-96f8-731797b27b46.png">

**Comment by begreatnic** [comment]
![screen shot 2017-07-23 at 10 48 27 am](https://user-images.githubusercontent.com/13004056/28500582-e0a592d2-6f98-11e7-8ec5-82d7f6abb0d9.png)
![screen shot 2017-07-23 at 10 39 33 am](https://user-images.githubusercontent.com/13004056/28500587-e0a790aa-6f98-11e7-9ce8-9720bb24d91f.png)
![screen shot 2017-07-23 at 10 39 27 am](https://user-images.githubusercontent.com/13004056/28500584-e0a641f0-6f98-11e7-9e4d-f47e47aa5272.png)
![screen shot 2017-07-23 at 10 38 04 am](https://user-images.githubusercontent.com/13004056/28500585-e0a6f3c0-6f98-11e7-9e0e-cb8a87dd1822.png)
![screen shot 2017-07-23 at 10 37 58 am](https://user-images.githubusercontent.com/13004056/28500586-e0a78254-6f98-11e7-8e11-2718147de9ee.png)
![screen shot 2017-07-23 at 10 37 44 am](https://user-images.githubusercontent.com/13004056/28500583-e0a5b3de-6f98-11e7-9fd2-69e272beffed.png)
![screen shot 2017-07-23 at 10 37 28 am](https://user-images.githubusercontent.com/13004056/28500588-e0ada9c2-6f98-11e7-8287-fb7090e61797.png)

[No picture] Popcorn

Please add all of these whenever you get the chance to. Thanks!

Also, I dragged all the files quick so there's two mailmans because of that.

**Comment by Croutonix** [comment]
I just added them thanks!

**Comment by Chew** [comment]
cup
<img width="383" alt="2488efc6ed339a5cfaad5e693b4120cf" src="https://user-images.githubusercontent.com/8278263/28502598-8658ac9c-6fbb-11e7-8478-a6e131c3b21e.png">

**Comment by MrJoCrafter** [comment]
New Words:
watering can
plate

**Comment by begreatnic** [comment]
Another word: Zoo
Again, thank you so much for doing this! I really appreciate all the work you've done for this.

Echo

**Comment by MrJoCrafter** [comment]
Another word: state

**Comment by Chew** [comment]
Since it's incredibly easy to suggest missing words, looks like this is going to be no longer in use. Sorry guys it's been a good run.
