### ISSUE TITLE
Missing Word List (Hive)

### ISSUE THREAD

**Issue by Chew** [Croutonix/dmtcheat#6]
## New Words

- None!

#### Copy-Paste Friendly
``

---

### Commit 3588f23

- [Coconut](#issuecomment-317285477)
- [Rectangle](#issuecomment-317285477)
- [House](#issuecomment-317285477)
- [Flamingo](#issuecomment-317285477)
- [Pencil](#issuecomment-317285477)
- [Cupcake](#issuecomment-317285477)
- [Cauldron](#issuecomment-317495323)
- [Game](#issuecomment-317495323)
- [sunglasses](#issuecomment-317902024)
- [kite](#issuecomment-317902024)
- [speaker](#issuecomment-317902024)
- [zombie](#issuecomment-317902298) (Thanks [MrJoCrafter](http://github.com/MrJoCrafter)) (No Screenshot)
- [axe](#issuecomment-317902298) (Thanks [MrJoCrafter](http://github.com/MrJoCrafter)) (No Screenshot)
- [torch](#issuecomment-317902298) (Thanks [MrJoCrafter](http://github.com/MrJoCrafter)) (No Screenshot)
- [guardian](#issuecomment-317902298) (Thanks [MrJoCrafter](http://github.com/MrJoCrafter)) (No Screenshot)
- [swing](#issuecomment-317902298) (Thanks [MrJoCrafter](http://github.com/MrJoCrafter)) (No Screenshot)

## Words Added
_Let's make a fun contest?_
[Chewsterchew](http://github.com/chewsterchew) - 11 Words
[MrJoCrafter](http://github.com/mrjocrafter) - 5 Words

**Comment by Chew** [comment]
Fun fact: all from one game xD

<img width="355" alt="1823de34a53426e43990e21c6c6f9e3a" src="https://user-images.githubusercontent.com/8278263/28503244-d1b01b82-6fc8-11e7-8487-0898efa2210b.png">
<img width="245" alt="848f46c87dddd75d34ea5dbe2c6e4e95" src="https://user-images.githubusercontent.com/8278263/28503245-d2f2763e-6fc8-11e7-872c-0c090c4ce701.png">
<img width="326" alt="5d657b23353e1560a1ff68bc860a2fed" src="https://user-images.githubusercontent.com/8278263/28503247-d40890c6-6fc8-11e7-8c27-7b59b55d88bc.png">
<img width="355" alt="28c69beb4ed26d04b433e26f610dee38" src="https://user-images.githubusercontent.com/8278263/28503248-d567c0e0-6fc8-11e7-84d8-e1e6ab85ebd6.png">
<img width="332" alt="9617bdb45f621a580615e7f2cf97e4fa" src="https://user-images.githubusercontent.com/8278263/28503252-e89fc09a-6fc8-11e7-92dc-389d407752b0.png">
<img width="355" alt="45d345bc1a812c00d1519ac88bf12be5" src="https://user-images.githubusercontent.com/8278263/28503253-e9ad9a52-6fc8-11e7-9fb7-b490f8e8279a.png">

**Comment by Chew** [comment]
<img width="355" alt="1f19ed543f45d71e4f094bf1efda1ad7" src="https://user-images.githubusercontent.com/8278263/28535903-a6f52be6-706b-11e7-98da-1835de674ea9.png">
<img width="308" alt="b0ee2fc66bb2e28140ec6f85eb3a4339" src="https://user-images.githubusercontent.com/8278263/28535906-a801f78a-706b-11e7-962b-8a954eea5042.png">

**Comment by Chew** [comment]
<img width="386" alt="6fb01bfa1024215404743e27647e7dbf" src="https://user-images.githubusercontent.com/8278263/28597918-20a4703c-7166-11e7-9a0c-0ce0c5c4b901.png">
<img width="307" alt="cb1540e7eb4d10fa3f4d776616a6efcf" src="https://user-images.githubusercontent.com/8278263/28597919-216fc0b6-7166-11e7-8589-30e4ce9f4109.png">
<img width="353" alt="b5510463ed92f6ebba599cb96a8088e3" src="https://user-images.githubusercontent.com/8278263/28597985-806d07ea-7166-11e7-9191-b0cc1c8483bf.png">

**Comment by MrJoCrafter** [comment]
zombie
axe
torch
guardian
swing

**Comment by Croutonix** [comment]
Chew I invited you to be a collaborator so you can add the words by yourself when you need. It will be less work than screenshotting each of them and adding links. I believe you play with MrJoCrafter so I didn't add him but tell me if you want me to add him too. 

If you update the word list you'll notice it can take a while (10+ minutes) before the website actually shows them, it's normal. I usually name the commit "Added x words" and write the words in the description. If the new word exceeds the minimum or the maximum set, you can change them in `dmtcheat.js`, I added comments so you'll know where to change the value. Shouldn't happen with Mineplex but maybe with Hive.

Thanks for helping me by the way! I hardly play Minecraft anymore so I don't have many chances to update the word lists.

**Comment by Chew** [comment]
Since it's incredibly easy to suggest missing words, looks like this is going to be no longer in use. Sorry guys it's been a good run.
