### ISSUE TITLE
Help us find other servers with pictionary-like games!

### ISSUE THREAD

**Issue by MrJoCrafter** [Croutonix/dmtcheat#8]
Let's start a race to who can find a server with another game like dmt or draw it.

Servers:
~~Mineplex - Draw My Thing~~
~~The Hive - Draw It~~
~~Hypixel - Guess my Build~~ thanks @SylveonBottle and @builder-247

**Comment by SeasonalFerret** [comment]
Hypixel has added Guess My Build. 
Basically "draw my thing" but in 3D.

**Comment by Chew** [comment]
Thanks for the tip, @SylveonBottle ! We added it in #12, thanks to @builder-247. Enjoy cheating and report words!
