### ISSUE TITLE
Single word copying

### ISSUE THREAD

**Issue by Chew** [Croutonix/dmtcheat#9]
Mineplex doesn't have multiple guesses (Not sure about hive) so we should add a way to click on a word to copy it. If you click a new word, the copied words reset, and you just copy once at a time.
I did a bad job of explaining but I tried.
~~Thanks guy who posted that

**Comment by Croutonix** [comment]
Sorry I'm a bit late but doesn't that feature already exists? You can click on any word in the list to copy it.

**Comment by Chew** [comment]
Well, currently, you click multiple words and they all get added to the clipboard. Mineplex only allows one word at a time, so I'm saying, when you click on a word, clear the clipboard and copy that word

**Comment by Croutonix** [comment]
When you click on a word in the list doesn't it copy only that word to your clipboard? Sorry I don't understand, it seems to work for me as you want it to work.

**Comment by Chew** [comment]
Oh.. I see. Then I think what I am proposing is remove the `Reset Copied Words` and only just copy the word and "reset it" when a new word is clicked

**Comment by Chew** [comment]
So basically when I click a different word, "Reset Copied Words" then copy the word I just clicked

**Comment by Croutonix** [comment]
Words' color changes to gray to show that you already tried them. The reset copied words button is almost useless, I don't see many cases where it would be needed, but it's already there so I won't remove it. The only problem is that the words you copied get resetted when you add more hints, I should fix that.

**Comment by Chew** [comment]
Okay I'm slowly understanding this. Can we just rename the button to "Reset Guessed Words" or something?
